<?php
/*
Plugin Name: Blogpocket LLMS Generator
Description: Genera el archivo llms.txt con las publicaciones seleccionadas, para su consumo por LLMs.
Version: 2.2.11
Author: Antonio Cambronero
*/

defined('ABSPATH') || exit;

// Opciones por defecto al activar
register_activation_hook(__FILE__, function () {
    add_option('bllms_enabled', true);
    add_option('bllms_post_types', ['post']);
    bllms_generate_file();

});

register_deactivation_hook(__FILE__, function () {
    delete_option('bllms_enabled');
    delete_option('bllms_post_types');
    $file = ABSPATH . 'llms.txt';
    if (file_exists($file)) unlink($file);

});

// Crear menú en el admin sidebar
add_action('admin_menu', function () {
    add_menu_page(
        'LLMS Generator',
        'LLMS Generator',
        'manage_options',
        'bllms-generator',
        'bllms_render_settings_page',
        'dashicons-media-text'
    );

});


// Hook para comprobar si se ha desactivado el plugin desde el panel y eliminar el archivo
add_action('admin_init', function () {
    register_setting('bllms_settings_group', 'bllms_enabled');
    register_setting('bllms_settings_group', 'bllms_post_types');

    if (isset($_GET['page']) && $_GET['page'] === 'bllms-generator' && isset($_GET['settings-updated'])) {
        if (get_option('bllms_enabled')) {
            bllms_generate_file();
        } else {
            $file = ABSPATH . 'llms.txt';
            if (file_exists($file)) unlink($file);
        }
    }
});

function bllms_render_settings_page() {
    ?>
    <div class="wrap">
        <h1>Blogpocket LLMS Generator</h1>
        <form method="post" action="options.php">
            <?php settings_fields('bllms_settings_group'); ?>
            <?php do_settings_sections('bllms_settings_group'); ?>

            <table class="form-table">
                <tr valign="top">
                    <th scope="row">Activar generación del archivo llms.txt</th>
                    <td><input type="checkbox" name="bllms_enabled" value="1" <?php checked(1, get_option('bllms_enabled', 1)); ?> /></td>
                </tr>
                <tr valign="top">
                    <th scope="row">Tipos de contenido a incluir</th>
                    <td>
                        <?php
                        $post_types = get_post_types(['public' => true], 'objects');
                        $selected = get_option('bllms_post_types', ['post']);
                        foreach ($post_types as $pt) {
                            echo '<label><input type="checkbox" name="bllms_post_types[]" value="' . esc_attr($pt->name) . '" ' . (in_array($pt->name, $selected) ? 'checked' : '') . '> ' . esc_html($pt->labels->name) . '</label><br>';
                        }
                        ?>
                    </td>
                </tr>
            </table>
            <?php submit_button(); ?>
        </form>
    </div>
    <?php
}

// Acciones al guardar, editar o borrar contenido
add_action('save_post', 'bllms_generate_file');
add_action('before_delete_post', 'bllms_generate_file');

// Función principal
function bllms_generate_file() {
    if (!get_option('bllms_enabled')) return;

    $post_types = get_option('bllms_post_types', ['post']);
    $file_path = ABSPATH . 'llms.txt';

    $lines = [];
    $lines[] = "Generated by Blogpocket LLMS Generator, this is an llms.txt file, meant for consumption by LLMs.";
    $lines[] = "";
    $lines[] = "The XML sitemap of this website can by found by following [this link](" . get_site_url() . "/sitemap_index.xml).";
    $lines[] = "";
    $lines[] = "# Blogpocket: Cómo hacer un blog con WordPress";
    $lines[] = "";

    foreach ($post_types as $type) {
        $posts = get_posts([
            'post_type' => $type,
            'post_status' => 'publish',
            'numberposts' => 50,
            'orderby' => 'date',
            'order' => 'DESC',
        ]);

        if ($posts) {
            $label = get_post_type_object($type)->labels->name;
            $lines[] = "## " . $label;

            $posts = array_reverse($posts);
            foreach ($posts as $p) {
                $url = get_permalink($p->ID);
                $title = addcslashes(html_entity_decode(wp_strip_all_tags($p->post_title), ENT_QUOTES | ENT_HTML5, 'UTF-8'), '\\`*_{}[]()#+-.!|');
                $excerpt = addcslashes(html_entity_decode(wp_strip_all_tags($p->post_excerpt), ENT_QUOTES | ENT_HTML5, 'UTF-8'), '\\`*_{}[]()#+-.!|');
                $excerpt = trim($excerpt);
                if (!empty($excerpt)) {
                    
                    $lines[] = "- [{$title}]({$url}): {$excerpt}";
                } else {
                    $lines[] = "- [{$title}]({$url})";
                }
            }
            $lines[] = "";
        }
    }

    $content = implode(PHP_EOL, $lines);
    $fh = fopen($file_path, 'wb');
    fwrite($fh, chr(0xEF) . chr(0xBB) . chr(0xBF)); // BOM
    fwrite($fh, $content);
    fclose($fh);
}